Areas/ProductManage/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Services;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers
{
    [Area("ProductManage")]
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly ProductService _productService;

        public ProductController(ILogger<ProductController> logger, ProductService productService)
        {
            _logger = logger;
            _productService = productService;
        }

        /**
            Có area: 
            Tìm file theo đường dẫn: /Areas/{AreasName}/Views/{ControllerName}/Action.cshtml
        */
        [HttpGet("danhsachsanpham.html", Name = "danhsachsanpham")]
        public IActionResult Index()
        {
            var products = _productService.ToList();
            return View(products); // => /Areas/ProductManage/Views/Product/Index.cshtml
        }
    }
}

Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using App.Services;

namespace App.Controllers
{
    [Route("he-mat-troi")]
    /**
        Route ở Controller này sẽ kết hợp với route ở action
        /he-mat-troi/[action]/...
    */
    public class PlanetController : Controller
    {
        private readonly ILogger<PlanetController> _logger;
        private readonly PlanetService _planetService;

        public PlanetController(ILogger<PlanetController> logger, PlanetService planetService)
        {
            _logger = logger;
            _planetService = planetService;
        }

        [Route("danhsachhanhtinh.html")]
        public IActionResult Index()
        {
            return View(_planetService);
        }

        [HttpGet("traidat.html")]
        public IActionResult Earth(int? id)
        {
            var planet = _planetService.Where(x => x.Id == id).FirstOrDefault();
            return View("Details", planet);
        }

        [Route("hanhtinh/[action]/{id:int?}", Name = "PlanetDetail")]
        public IActionResult Details(int? id)
        {
            var planet = _planetService.Where(x => x.Id == id).FirstOrDefault();
            return View(planet);
        }
    }
}

/**
    Controller, Action, Area => [controller], [action], [area]
    vd: [Route("[controller]-[action].html")] => /Planet-Details.html
    [Route("[controller]-[action].html")]
    Name = "PlanetDetail" => @Url.RouteUrl(Name) => Url của action này
*/

Pages/ChuyenHuong.cshtml
@page "/chuyenhuong.html"
@{
    Layout=  "_Layout";
}
<h1>Các phương thức để Redirect: Url.Action && Anchor taghelper</h1>

@{
    var urlToEarth = Url.Action("Details", "Planet", new {id = 3});
    var urlToPrivacy = Url.Action("Privacy");
    var urlToActionInArea = Url.Action("Index", "Product", new {area = "ProductManage"});
    var urlByRouteName = Url.RouteUrl("danhsachsanpham");
    // hoặc: Url.RouteUrl("default", new {action = "HelloView", controller = "Home", ...});
}
<h4>Dùng Url.Action</h4>
<div class="text-center">
    <a href="@urlToEarth" class="btn btn-success btn-md">Test Url.Action</a>
    <a href="@urlToPrivacy" class="btn btn-warning btn-md">Test Url.Action</a>
    <a href="@urlToActionInArea" class="btn btn-danger btn-md">Test Url.Action in area</a>
    <a href="@urlByRouteName" class="btn btn-primary btn-md">Test Url.Action by route name</a>
</div>

<h4>Dùng Anchor Taghelper</h4>
<div class="text-center mt-2">
    <a asp-controller="Planet" asp-action="Details" asp-route-id="3" class="btn btn-success btn-md">Test Anchor Taghelper</a>
    <a asp-action="Privacy" class="btn btn-warning btn-md">Test Anchor Taghelper</a>
    <a asp-area="ProductManage" asp-controller="Product" asp-action="Index" class="btn btn-danger btn-md">Test Anchor Taghelper with Area</a>
    <a asp-route="danhsachsanpham" class="btn btn-primary btn-md">Test Anchor Taghelper with Route name</a>
</div>

<h4>Dùng asp-all-route-data khi có quá nhiều route data cần truyền</h4>
<div class="text-center mt-2">
    @{
        var routeData = new Dictionary<string, string>() {
            {"id", "2"},
            {"name", "John Smith"},
            {"email", "vn.quyensinh@gmail.com"}
        };
    }
    <a asp-route="danhsachsanpham" asp-all-route-data="@routeData" class="btn btn-outline-danger btn-lg">Test</a>
</div>